version: 1
disable_existing_loggers: True

formatters:
  formatter:
    format: '[{asctime}] #{levelname:<8} {filename:<17}:{lineno:4} - <{funcName}> - {message}'
    datefmt: '%Y.%m.%d %H:%M:%S'
    style: '{'

filters:
  get_cert_filter:
    (): logging_setting.filters.GetCertFilter

handlers:
  stdout:
    class: logging.StreamHandler
    formatter: formatter
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: formatter
    filename: /app/logs/app.log
    maxBytes: 10485760
    backupCount: 3
    mode: 'a'

  telegram:
    class: logging_setting.handlers.TelegramAsyncHandler
    formatter: formatter
    level: ${LOG_LEVEL}
    bot_token: ${BOT_TOKEN}
    chat_id: ${LOG_TG_CHAT_ID}
    thread_id: ${LOG_TG_THREAD_ID}
    filters: [get_cert_filter]


loggers:

  queues.que_utils:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  handlers.temp_handlers:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  handlers.admin_handlers:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  middlewares.outer:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  handlers.user_handlers:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  handlers.other_handlers:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  config_data.config:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  filters.filters:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  keyboards.keyboard_utils:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  keyboards.keyboards:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  keyboards.set_menu:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  lexicon.lexicon_ru:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  states.states:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  utils.utils:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file, telegram ]
    propagate: no

  logging_setting.handlers:
    level: ${LOG_LEVEL}
    handlers: [ stdout, file ]
    propagate: no

  __main__:
    level: ${LOG_LEVEL}
    handlers: [stdout, file]
    propagate: no

root:
  level: ${LOG_LEVEL}
  handlers: [stdout, file]