version: 1
disable_existing_loggers: True

formatters:
  formatter:
    format: '[{asctime}] #{levelname:<8} {filename:<17}:{lineno:4} - <{funcName}> - {message}'
    datefmt: '%Y.%m.%d %H:%M:%S'
    style: '{'

handlers:
  stdout:
    class: logging.StreamHandler
    formatter: formatter
    stream: ext://sys.stdout

loggers:

  queues.que_utils:
    level: ${LOG_LEVEL}
    handlers: [ stdout ]
    propagate: no

  handlers.admin_handlers:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  middlewares.outer:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  handlers.user_handlers:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  handlers.other_handlers:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  config_data.config:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  filters.filters:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  keyboards.keyboard_utils:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  keyboards.keyboards:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  keyboards.set_menu:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  lexicon.lexicon_ru:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  states.states:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no

  utils.utils:
      level: ${LOG_LEVEL}
      handlers: [ stdout ]
      propagate: no
  __main__:
    level: ${LOG_LEVEL}
    handlers: [stdout]
    propagate: no

root:
  level: ${LOG_LEVEL}
  handlers: [stdout]