version: 1
disable_existing_loggers: True

formatters:
  formatter:
    format: '[{asctime}] #{levelname:<8} {filename:<17}:{lineno:4} - <{funcName}> - {message}'
    datefmt: '%Y.%m.%d %H:%M:%S'
    style: '{'

handlers:
  stdout:
    class: logging.StreamHandler
    formatter: formatter
    stream: ext://sys.stdout

root:
  level: ${LOG_LEVEL}
  handlers: [stdout]