# PROD_COMPOSE
services:
  main:
    image: niwibonihs/bot_get_cert:v3.2
    container_name: Your-Container-Name
    user: "1000:1000" # Дать UID/GID контейнеру для прав на нужные директории на хосте при монтировании
    restart: "unless-stopped"
    env_file: .env
    depends_on:
      - "test_redis_fsm"
    logging:
      driver: json-file
      options:
        max-size: "7m"
        max-file: "3"
    volumes:
      - data:/app/data  # Монтируем папку для обмена файлами
      - ./logs:/app/logs # Монтируем папку для логов
    networks:
      - Your-Network-Name
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  test_redis_fsm:
    image: "redis:7"
    container_name: YourRedisFSM
    restart: "unless-stopped"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Монтируем конфигурационный файл
      - redis_data:/data  # Volume для данных Redis
    command: redis-server /usr/local/etc/redis/redis.conf  # Используем конфигурационный файл
    ports:
      - 127.0.0.1:6382:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - Your-Network-Name
    deploy:
      resources:
        limits:
          memory: 16M

volumes:
  redis_data:
  data:

networks:
  Your-Network-Name:
    name: Your-Network-Name
